
services:
  # selenium:
  #   image: seleniarm/standalone-chromium:latest
  #   logging:
  #     driver: none
  #   ports:
  #     - "4444:4444"  # Selenium WebDriver
  #     - "5900:5900"  # VNC Server for UI debugging
  #   environment:
  #     - SE_SESSION_TIMEOUT=600
  #     - SE_NODE_MAX_SESSIONS=20
  #   privileged: true
  #   shm_size: 2g
  #   stdin_open: true
  #   tty: true
  #   networks:
  #     - app_network
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_SESSION_TIMEOUT=600
      - SE_NODE_MAX_SESSIONS=20

  chrome2:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_SESSION_TIMEOUT=600
      - SE_NODE_MAX_SESSIONS=20

  chrome3:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_SESSION_TIMEOUT=600
      - SE_NODE_MAX_SESSIONS=20

  chrome4:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_SESSION_TIMEOUT=600
      - SE_NODE_MAX_SESSIONS=20

  chrome5:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_SESSION_TIMEOUT=600
      - SE_NODE_MAX_SESSIONS=20

  chrome6:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_SESSION_TIMEOUT=600
      - SE_NODE_MAX_SESSIONS=20
volumes:
  postgres: {}
  redis: {}

networks:
  app_network:
    driver: bridge

