
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4445:4444"
      - "4443:4443"
    environment:
      - SE_ROUTER_USERNAME=your_username
      - SE_ROUTER_PASSWORD=your_password

  chrome:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_SESSION_TIMEOUT=600
      - SE_NODE_MAX_SESSIONS=20

  chrome2:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_SESSION_TIMEOUT=600
      - SE_NODE_MAX_SESSIONS=20

  chrome3:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_SESSION_TIMEOUT=600
      - SE_NODE_MAX_SESSIONS=20

  chrome4:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_SESSION_TIMEOUT=600
      - SE_NODE_MAX_SESSIONS=20

  chrome5:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_SESSION_TIMEOUT=600
      - SE_NODE_MAX_SESSIONS=20

  chrome6:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_SESSION_TIMEOUT=600
      - SE_NODE_MAX_SESSIONS=20
volumes:
  postgres: {}
  redis: {}

networks:
  app_network:
    driver: bridge

